-- Eliminar tablas si ya existen (para reiniciar el esquema)
DROP TABLE IF EXISTS STUDENTS_COURSES;
DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS INSTRUCTORS;
DROP TABLE IF EXISTS STUDENTS;

-- Tabla de estudiantes
CREATE TABLE STUDENTS (
    STUDENT_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    AGE INTEGER,
    EMAIL VARCHAR(50),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de instructores
CREATE TABLE INSTRUCTORS (
    INSTRUCTOR_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de cursos
CREATE TABLE COURSES (
    COURSE_ID INTEGER PRIMARY KEY,
    COURSE_NAME VARCHAR(100),
    COURSE_DESCRIPTION TEXT,
    INSTRUCTOR_ID INTEGER,
    DURATION_HOURS INTEGER,
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTORS(INSTRUCTOR_ID)
);

-- Tabla de inscripciones estudiantes-cursos
CREATE TABLE STUDENTS_COURSES (
    STUDENTS_COURSES_ID INTEGER PRIMARY KEY,
    STUDENT_ID INTEGER,
    COURSE_ID INTEGER,
    ENROLLMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENTS_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);